services:
  task-management-app:
    build:
      context: ./app
      dockerfile: ../docker/app/Dockerfile
    restart: on-failure
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_APP_BACKEND_URL=http://localhost:5050

  task-management-api:
    depends_on:
      task-management-database:
        condition: service_healthy
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile
    restart: on-failure
    ports:
      - "5050:5050"
    volumes:
      - ./api:/api
    environment:
      - NODE_ENV=development

  task-management-database:
    image: postgres
    restart: on-failure
    shm_size: 128mb
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app
    volumes:
      - ./task-management-data:/var/lib/postgresql/data
      - ./docker/database/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  task-management-data:
